# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ksharlen <ksharlen@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/07/25 13:07:45 by ksharlen          #+#    #+#              #
#    Updated: 2019/07/25 14:39:01 by ksharlen         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME := ft_printf

DIR_BONUS := bonus/
DIR_BUF := buf/
DIR_SRC_NUM_TO_STR := src_num_to_str/
DIR_SRC := src/

SRC_MAIN := 		ft_printf.c\
						other.c\
						work_spec_form.c\
						work_to_format.c

SRC_BUF	:=			buf.c\
						work_buf_by_hand.c

SRC_BONUS := 		color.c\
						date.c\
						for_date.c\
						invisible_sym.c\
						size_formats.c\
						utf_8.c\
						work_wchar.c\
						write_to_file.c

SRC_NUM_TO_STR :=	base_to_str.c\
						char_to_str.c\
						double_to_str.c\
						double_to_str2.c\
						double_to_str3.c\
						int_to_str.c\
						long_arithmetic.c\
						not_spec.c\
						other_spec.c\
						select_num_sys.c\
						str_to_str.c

SRCS_FT_PRINTF := $(SRC_MAIN) $(SRC_BUF) $(SRC_BONUS) $(SRC_NUM_TO_STR)
DIRS_FT_PRINTF := $(DIR_SRC) $(addprefix $(DIR_SRC), $(DIR_MAIN) $(DIR_BUF) $(DIR_BONUS) $(DIR_SRC_NUM_TO_STR))
